import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const jetbrains = localFont({
	variable: '--font-jetbrains',
	src: [
		{
			path: '../public/fonts/JetBrainsMono-Italic.woff2',
			weight: '400',
			style: 'italic'
		},
		{
			path: '../public/fonts/JetBrainsMono-SemiBold.woff2',
			weight: '600'
		},
		{
			path: '../public/fonts/JetBrainsMono-Bold.woff2',
			weight: '700'
		},
		{
			path: '../public/fonts/JetBrainsMono-BoldItalic.woff2',
			weight: '700',
			style: 'italic'
		}
	]
});

const roundo = localFont({
	variable: '--font-roundo',
	src: [
		{
			path: '../public/fonts/Roundo-Light.woff2',
			weight: '300'
		},
		{
			path: '../public/fonts/Roundo-Regular.woff2',
			weight: '400'
		},
		{
			path: '../public/fonts/Roundo-SemiBold.woff2',
			weight: '600'
		},
		{
			path: '../public/fonts/Roundo-Medium.woff2',
			weight: '500'
		}
	]
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${jetbrains.variable} ${roundo.variable}`}>
			<body className="font-roundo">{children}</body>
		</html>
	);
}
